#ifndef RED_O_LATOR_EVENTS_H
#define RED_O_LATOR_EVENTS_H

enum Events {
    OPEN = wxID_OPEN,
    EXIT = wxID_EXIT,
    ABOUT = wxID_ABOUT,
    TOGGLE_ADDRESS_MARGIN = 1,
    SELECT_KERNEL,
    SELECT_WAVEFRONT,
    SELECT_WORK_ITEM_X,
    SELECT_WORK_ITEM_Y,
    SELECT_WORK_ITEM_Z,
    REQUEST_MEMORY,
    ATTACH,
    PAUSE,
    RESUME,
    STEP,
    STOP,
};

#endif  // RED_O_LATOR_EVENTS_H
