#ifndef RED_O_LATOR_KERNELARGUMENTKIND_H
#define RED_O_LATOR_KERNELARGUMENTKIND_H

enum KernelArgumentKind {
    SCALAR, VECTOR, STRUCT, IMAGE, SAMPLER, EVENT, POINTER
};

#endif  // RED_O_LATOR_KERNELARGUMENTKIND_H
